#!/usr/bin/env ruby
# encoding: UTF-8
require 'fileutils'

src = File.join(Dir.home, 'ICARE_EDITIONS', 'livres', 'musique', 'xDev','scripts','music-score','Manuel.pdf')
dst = File.join(__dir__,'Manuel.pdf')

if File.exist?(src)
  File.delete(dst) if File.exist?(dst)
  puts "Copie de #{src} vers #{dst}"
  FileUtils.copy(src,dst)
  if File.exist?(dst)
    puts "Copie effectuée avec succès."
  else
    puts "# Bizarrement, la copie n'a pas pu se faire…"
  end
else
  puts "# Impossible de trouver la source #{src.inspect}…"
end
